part of 'consultation_screen_widget.dart';

Widget _buildPopupDialog(BuildContext context) {
  final TextEditingController gdaController = TextEditingController();

  List<String> countries = [
    'سيدي مسعود',
    'هندي الزيتونة',
    'عين بومرّة',
    'أولاد خلف الله',
    'وشتاتية',
    'الفريوات',
    'الدخيلة',
    'القفي',
    'همّاد فرنيز',
    'همّاد الدخايلية',
    'غويرقة',
    'الخضر',
    'سرديانة 1',
    'العفاسة',
    'سرديانة 2',
    'الزّهّار',
    'الوديّات',
    'الجواودة',
    'أولاد بن حيمد',
    'المعراجي',
    'بير شهيدة',
    'المشنوقة',
    'أولاد الحاج',
    'سعايدية',
    'الدرابلية',
    'قليب السّبط',
    'العوايد',
    'هندي الرقّاص',
    'رواونة-طرابلسية',
    'العرفات',
    'أولاد شهيب',
    'بودبوس',
    'أولاد أحمد الصغير',
    'الهواينية',
    'العبابسة',
    'الخريوع',
    'العرايسية',
    'هماد- فريوات',
    'فطناسة',
    ' الدرع',
    'الخشم',
    'أولاد العيساوي',
    'العواديد',
    'الفجارنية',
    'العجيلات',
    'أولاد الحاج عمار',
    'عين زانة',
    'الزبارة للشراب',
    'عين الكدية',
    'المسلسل الشريشيرة',
    'أولاد خليف',
    'إدمان الحاسي',
    'أولاد خلف الله',
    'جليل عين البيضاء',
    'العالية',
    'الرميل',
    'المرمر ( ميزاي)',
    'فم النقاش (العبادلية)',
    'المحافيظ',
    'الرحمة',
    'الزملة',
    'العنق',
    'أولاد فرحات',
    'المرايحية',
    'الجباس',
    'أولاد ضيف الله',
    'المنزل العالية',
    'عين مستور',
    'أولاد تليل',
    'جبل الريحان',
    'قصر اللمسة',
    'لبيرة - زغدود',
    'هندي العمري',
    'أولاد بامر',
    'السطوح',
    'الـحريــة',
    'القواعد',
    'العباريش',
    'جبل السرج',
    'عريبة',
    'الدبابشة',
    'مسيوتة القطار',
    'القطار أولاد عمر',
    'صيادة ',
    'أولاد بن جـدو',
    'البصيلات',
    'الشواشي 2',
    'قصرسويسين',
    'أولاد عامر',
    'السرجة 2',
    'السرجة 1',
    'للة سالمة 2',
    'القنطرة - هنشير الشط',
    'واد الفول',
    'الشواشي 1',
    'المناسة',
    'اللواتة',
    'الدغيمة',
    'الخوالدية',
    ' الكبارة 2',
    'صالح مختارة',
    'عين سلطان',
    'الكبارة',
    'الفساقي',
    'القصور',
    'خميس العلويني',
    'كاف الزاهي',
    'قرعة البليدات 2',
    'أولاد سويس',
    'العجابنة',
    'ثامر',
    'العيايدة',
    'الخبنة',
    'المشرطات',
    'بئر مسيكين',
    'بئر الجديد المدرسة',
    'بوساري',
    'بئر الدولة الصعادلية',
    'بئر المعيصرة',
    'الدخيلة',
    'الزقب',
    'النصرزعفرانة',
    'أولاد عباس',
    'أولاد جمعة',
    'بوجدارية',
    'الفتح',
    'الفريجات 2',
    'القطيطير-اولا عاشور',
    'مرزوق الفرخ',
    'بئر هويدي',
    'الرماضنية',
    'الرويسات',
    'مطايرية',
    'هماد الجلولي',
    'البريكات المدينة',
    'بئر الضواهر',
    'بريكات العرقوب',
    'المخصومة',
    'العرقوب 2',
    'الحمباز',
    'الشوامخ',
    'الحسيان ',
    'غنزور',
    'شاكر',
    'جبل وسلات',
    'مقرة',
    'ذراع التمار',
    'الذويبات',
    'العزاعزة',
    'الفجيج',
    'الحميدات',
    'بئر الحاج صادق',
    'بوقبرين',
    'المريقب',
    'اولاد نهار',
    'كبارة 3',
  ];
  return AlertDialog(
    title: Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(AppLocalizations.of(context)!.gdaTitre),
        IconButton(
          icon: const Icon(Icons.close),
          onPressed: () {
            Navigator.of(context).pop();
          },
        )
      ],
    ),
    content: Column(
      mainAxisSize: MainAxisSize.min,
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        const Divider(
          color: Colors.white12,
        ),
        SearchField<String>(
          controller: gdaController,
          hint: AppLocalizations.of(context)!.rechercheTitre,
          searchInputDecoration: const InputDecoration(
              prefixIcon: Icon(Icons.search), focusColor: Colors.white),
          // suggestionItemDecoration: const BoxDecoration(color: Colors.white),
          suggestions: countries
              .map(
                (e) => SearchFieldListItem<String>(
                  e,
                  item: e,
                  child: Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Row(
                      children: [
                        Container(
                          decoration: BoxDecoration(
                            border: Border.all(color: Colors.black),
                            shape: BoxShape.circle,
                          ),
                          height: 20.0,
                          width: 20.0,
                          child: const Center(),
                        ),
                        const SizedBox(
                          width: 10,
                        ),
                        Text(e)
                      ],
                    ),
                  ),
                ),
              )
              .toList(),
        ),
      ],
    ),
    actions: <Widget>[
      TextButton(
        onPressed: () {
          Navigator.of(context).pop(gdaController.text);
        },
        child: Text(AppLocalizations.of(context)!.validerTitre),
      ),
    ],
  );
}
